### ISSUE TITLE
About the data used in the project

### ISSUE THREAD

**Issue by mjwang1010** [stineb/soilm_global#1]
Hi, Ben,

Thanks for your sharing. It is an amazing project. I was wondering if I could directly use the data ('df_modobs_fluxnet2015_s16_with_SWC_v5.Rdata') here in my study. 

In addition, I have two questions about the data. 1) What does the 'ppfd' in the data frame refer to? (intercepted PAR or incoming PAR (PPFD_IN)) 2) Is the daily 'fpar' obtained by linearly interpolating the 4-day fpar product? I just want to check my point. Thank you!

Mengjie

**Comment by stineb** [comment]
Hi Mengjie,

Great to see interest in my work. This here is a project that I am currently working on. So before I can give you more support, I would like to know what your project is about, what part of my analyses you are interested in and how you are planning to use code from this repository. Let me know if I can assist more directly and we can think of a collaboration. 

Cheers,
beni

**Comment by mjwang1010** [comment]
Dear Beni, 

Sorry for a late reply. I wrote an email to you to inform my situation. Hope that would be OK. Thank you!

Best,
Mengjie
